### ISSUE TITLE
all scripts fail

### ISSUE THREAD

**Issue by hagar-qim** [Wurmcraft/WurmTweaks2#8]
the log file is full of lines like (note that Thaumcraft is installed) 
_[20:53:38] [main/INFO] [WurmScript]: Thaumcraft.ws [5]: ReferenceError: "addLootBagItem" is not defined in <eval> at line number 1_

where you'd expect the minecraft.ws script to run, you get errors like 
_[20:53:38] [main/INFO] [STDERR]: [com.wurmcraft.wurmtweaks.script.ScriptFunctionWrapper:apply:24]: java.lang.StringIndexOutOfBoundsException: String index out of range: -14
[20:53:38] [main/INFO] [STDERR]: [com.wurmcraft.wurmtweaks.script.ScriptFunctionWrapper:apply:24]: 	at java.lang.String.substring(Unknown Source)
[20:53:38] [main/INFO] [STDERR]: [com.wurmcraft.wurmtweaks.script.ScriptFunctionWrapper:apply:24]: 	at com.wurmcraft.wurmtweaks.utils.StackHelper.convert(StackHelper.java:41)
[20:53:38] [main/INFO] [STDERR]: [com.wurmcraft.wurmtweaks.script.ScriptFunctionWrapper:apply:24]: 	at com.wurmcraft.wurmtweaks.script.ModSupport.isValid(ModSupport.java:27)
[20:53:38] [main/INFO] [STDERR]: [com.wurmcraft.wurmtweaks.script.ScriptFunctionWrapper:apply:24]: 	at com.wurmcraft.wurmtweaks.script.ModSupport.isValid(ModSupport.java:72)
[20:53:38] [main/INFO] [STDERR]: [com.wurmcraft.wurmtweaks.script.ScriptFunctionWrapper:apply:24]: 	at com.wurmcraft.wurmtweaks.script.support.Minecraft.addOreEntry(Minecraft.java:70)_

none of the vanilla test recipes are available

**Comment by Wurmatron** [comment]
WurmTweaks Version?

**Comment by Wurmatron** [comment]
Seems like you are running a .2.* version which I removed from curseforge due to being full of bugs after the rewrite, converted back to older 0.1 base,

**Comment by hagar-qim** [comment]
the jar comes from curseforge : WurmTweaks-0.0.1.6.jar

**Comment by Wurmatron** [comment]
Sorry about that i forgot that the default scripts are linked to the version of the rewrite causing a ton of script conflicts
